# Generated by Django 3.1.7 on 2021-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
