# Generated by Django 3.1.7 on 2021-02-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ogrenci', 'Öğrenci'), ('egitmen', 'Eğitmen')], default=1, max_length=20),
        ),
    ]
