# Generated by Django 3.1.7 on 2021-02-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('question', models.TextField()),
                ('A_choice', models.TextField()),
                ('B_choice', models.TextField()),
                ('C_choice', models.TextField()),
                ('D_choice', models.TextField()),
                ('E_choice', models.TextField()),
                ('trueChoice', models.CharField(choices=[('A_choice', 'A'), ('B_choice', 'B'), ('C_choice', 'C'), ('D_choice', 'D'), ('E_choice', 'E')], default=1, max_length=20)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'unique_together': {('ques_no', 'exam_id')},
            },
        ),
    ]
