# Generated by Django 3.1.7 on 2021-02-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210223_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default='2021-02-20 20:00:00'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='st_date',
            field=models.DateTimeField(default='2021-02-20 20:00:00'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_no',
            field=models.IntegerField(default=1),
        ),
    ]
