# Generated by Django 3.1.7 on 2021-02-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20210224_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
