# Generated by Django 3.1.7 on 2021-02-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_exam_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='owner_id',
        ),
    ]
