# Generated by Django 3.1.7 on 2021-02-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_exam_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='owner_id',
            new_name='owner_email',
        ),
    ]
