# Generated by Django 3.1.7 on 2021-02-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210223_0406'),
        ('exam', '0016_auto_20210224_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='owner_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.user'),
        ),
    ]
