# Generated by Django 3.1.7 on 2021-02-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210223_0406'),
        ('exam', '0017_auto_20210224_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='owner_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('partc_email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default=1, max_length=20)),
                ('owner_email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('ques_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
